grade_one = Genre.create(name: "アニメ＆ゲーム")
grade_two = Genre.create(name: "スポーツ")
grade_three = Genre.create(name: "芸能")
grade_four = Genre.create(name: "ライフスタイル")
grade_five = Genre.create(name: "社会")
grade_six = Genre.create(name: "文系学問")
grade_seven = Genre.create(name: "理系学問")